### ISSUE TITLE
缺少动态链接库？

### ISSUE THREAD

**Issue by JoeZing** [TianLiangZhou/ffi-pinyin#2]
环境：Docker image：php:8.3.3-alpine；已经安装FFI扩展；
根据示例运行后提示：
```
Failed loading 'xxx/vendor/meshell/ffi-pinyin/lib/libffi_pinyin.so' (Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by xxx/vendor/meshell/ffi-pinyin/lib/libffi_pinyin.so))
```

```
ldd xxx/vendor/meshell/ffi-pinyin/lib/libffi_pinyin.so
提示 ：
unsupported relocation type 6
```

是这个so不支持我运行的环境架构？

我的docker是安装在Mac m2 max上，ARM架构

**Comment by TianLiangZhou** [comment]
我没有在docker下面测试过，看样子是你没有ld-linux-x86-64.so这个库，下面是我在我服务器执行ldd命令的结果。你可以docker exec 进去看看so的链接是咋样的。
        git:(main) ✗ ldd libffi_pinyin.so
	linux-vdso.so.1 (0x00007fffea14b000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f747866a000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f7478665000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f7478660000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f747865b000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f7477fd7000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f747869d000)

**Comment by TianLiangZhou** [comment]
@JoeZing 看看这个https://stackoverflow.com/questions/68630526/lib64-ld-linux-x86-64-so-2-no-such-file-or-directory-error

**Comment by JoeZing** [comment]
那就是编译的so不支持arm架构了，这个so是否能交叉编译使其能多平台使用，感谢。

**Comment by TianLiangZhou** [comment]
@JoeZing 你看下 我发得这个链接，改下docker的启动方式。
docker run --platform linux/x86_64 <image>

**Comment by JoeZing** [comment]
模拟使用 x86环境运行没问题，但这个只能临时解决，毕竟还是会影响性能以及其它包兼容性的问题，希望大佬能考虑下交叉编译。

**Comment by TianLiangZhou** [comment]
@JoeZing 你自己可以编译个，我这边没有arm的环境。要不你就直接原生运行，不要用docker。原生库里面有arm Mac的动态库的。
